spring:
  application:
    host: http://localhost:8080
    name: security-microservice
    jwt:
      secret-key: mySuperSecretKeyWithAtLeast32Characters1234567890
      expiration: 300000
    apis:
      users:
        base-path: /api/v1/users
        endpoints:
          registration: /registration
          recovery-password: /recovery/password
    client: #indicates if the client is active and what is the host
      active: true
      host: http://localhost:4000
      endpoints:
        registration: /registration
        recovery-password: /recovery-password
  datasource:
    url: jdbc:postgresql://localhost:5432/security_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: notificaciones.automaticas.jl@gmail.com
    password: tdfo htol gvvb gthd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
#Open api configs
springdoc:
  swagger-ui:
    enabled: true
  packages-to-scan: com.example.securitymicroservice.controllers
  api-docs:
    enabled: true